<?php

namespace PHPMaker2025\perpus2025baru;

// Page object
$Suratket = &$Page;
?>
<?php
$Page->showMessage();
?>
<?php
ob_end_clean(); // don't forget this at the beginning
include('src/koneksi.php');
require('plugins/tanggal.php');
require('plugins/fpdf/fpdf.php'); // it is generated by Masino Extensions for PHPMaker 2021
$Nomor_Surat = $_GET['Nomor_Surat'];

$pdf = new \FPDF(); // we use back slash in order to avoid error, since PHPMaker 2021 uses namespace

// Add first pagen
$pdf->AddPage('P', 'A4');

// Set initial x and y position per page
$y_axis_initial = 15;
$x_axis_initial = 27;

// Set Font Name and Size
$pdf->SetFont('Arial', '', 14);

// Set Y and X initial position
$pdf->SetY($y_axis_initial);
$pdf->SetX($x_axis_initial);

// Print it out now ...
$pdf->Image('../perpus.puskom.uncen.ac.id/images/logouncen.png', 5, 14, -400);
$pdf->Cell(170, 4, "KEMENTERIAN PENDIDIKAN, KEBUDAYAAN, RISET, DAN TEKNOLOGI", 0, 0, 'C', 0); // left-align, width: 170
$pdf->ln(5);
$pdf->SetFont('Arial', '', 15);
$pdf->Cell(190, 5, "UNIVERSITAS CENDERAWASIH", 0, 0, 'C', 0); // left-align, width: 170
$pdf->SetFont('Arial', 'B', 9);
$pdf->ln(5);
$pdf->Cell(190, 5, "Jalan Kampwolker, Kelurahan Yabansai Distrik Heram, Jayapura-Papua", 0, 0, 'C', 0); // left-align, width: 170
$pdf->ln(3);
$pdf->SetFont('Arial', '', 8);
$pdf->Cell(180, 9, "Laman  http://www.uncen.ac.id", 0, 0, 'C', 0); // left-align, width: 170
$pdf->Line(5, 36, 205, 36);
$pdf->ln(15);
$pdf->SetFont('Arial', 'BU', 14);
$pdf->Cell(180, 4, "SURAT KETERANGAN BEBAS PERPUSTAKAAN", 0, 0, 'C', 0); // left-align, width: 170
$pdf->ln(7);
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(135, 4, "Nomor :", 0, 0, 'C', 0);
//$query = "select * from surat_tugas where no_surat='$no_surat'";
$query = mysqli_query($con, "select * from vsrtket  where Nomor_Surat='$Nomor_Surat'");
while ($row = mysqli_fetch_array($query)) {
    //$pdf->Cell(10, 9, "", 0, 0, 'L', 0);
    include('plugins/function.php');
    $pdf->Cell(-70, 4, $row['Nomor_Surat'] . "/UN20.5.1/KM/2024", 0, 0, 'C', 0);
    //include('plugins/function.php'); 
    $pdf->ln(14);
    $pdf->SetFillColor(224, 835, 755);
    $x_axis_initial = 20;
    $pdf->SetX($x_axis_initial);
    $pdf->SetFont('Arial', '', 12);
    $pdf->Cell(70, 4, "Kepala Unit Pelaksana Teknis Perpustakaan Universitas Cenderawasih Jayapura,", 0, 0, 'J', 0);
    $pdf->ln(7);
    $pdf->SetX($x_axis_initial);
    $pdf->Cell(70, 4, "menerangkan bahwa,", 0, 0, 'L', 0);
    $pdf->SetFillColor(224, 835, 755);
    $pdf->ln(10);
    $pdf->SetX($x_axis_initial);
    $pdf->Cell(45, 9, "Nama", 0, 0, 'L', 0);
    $pdf->Cell(45, 9, ":  " . $row['Nama_Mahasiswa'], 0, 0, 'L', 0);
    $pdf->ln(10);
    $pdf->SetX($x_axis_initial);
    $pdf->Cell(45, 9, "Nomor Anggota", 0, 0, 'L', 0);
    $pdf->Cell(45, 9, ":  " . $row['No_Reg_Anggota'], 0, 0, 'L', 0);
    $pdf->ln(10);
    $pdf->SetX($x_axis_initial);
    $pdf->Cell(45, 9, "Fakultas/ Jurusan", 0, 0, 'L', 0);
    $pdf->Cell(147, 9, ":  " . $row['Nama_Fakultas'] . " / " . $row['Nama_Program_Studi'], 0, 0, 'L', 0);
    $pdf->ln(10);
    $pdf->SetX($x_axis_initial);
    $pdf->Cell(45, 9, "Program Studi/ Jenjang", 0, 0, 'L', 0);
    $pdf->Cell(45, 9, ":  " . $row['Nama_Program_Studi'] . " / " . $row['Jenjang'], 0, 0, 'L', 0);
    // $pdf->ln(10);
    // $pdf->Cell(30, 9, "Program Studi", 0, 0, 'L', 0);
    // $pdf->Cell(55, 9, $row['Nama_Mahasiswa'], 0, 0, 'C', 0);
    // //$pdf->Cell(90, 9, $row1['Nama_Mahasiswa'] . " / " . $row1['NIP'], 1, 0, 'L', 0);
    // $pdf->Cell(55, 9, $row['Nama_Pejabat'], 0, 0, 'C', 0);
    // $pdf->Cell(30, 9, $row1['Jabatan'], 1, 0, 'C', 0);
    $pdf->Image('../perpus.puskom.uncen.ac.id/file.png', 70, 160, -150);
    $pdf->ln(15);
    $pdf->SetFont('Arial', '', 12);
    $pdf->SetX($x_axis_initial);
    $pdf->Cell(190, 4, "Telah mengembalikan semua buku pinjaman pada Unit Pelaksana Teknis Perpustakaan", 0, 0, 'J', 0); // left-align, width: 170
    $pdf->ln(7);
    $pdf->SetX($x_axis_initial);
    $pdf->Cell(190, 4, "Universitas Cenderawasih Jayapura.", 0, 0, 'L', 0);
    $pdf->ln(7);
    $pdf->SetX($x_axis_initial);
    $pdf->Cell(190, 9, "Demikian Surat Keterangan ini dibuat untuk dapat dipergunakan sebagaimana mestinya.", 0, 0, 'J', 0);
    $pdf->ln(20);
    $pdf->Cell(100, 9, "", 0, 0, 'L', 0); // left-align, width: 170
    $pdf->Cell(5, 9, "Jayapura, " . tanggal_indonesia($row['Tanggal_Surat']), 0, 0, 'L', 0); // left-align, width: 170
}
$pdf->ln(4);
$pdf->Cell(100, 9, "", 0, 0, 'L', 0); // left-align, width: 170
//$pdf->Cell(5, 9, "an. Rektor", 0, 0, 'L', 0); // left-align, width: 170
$pdf->ln(5);
$pdf->Cell(100, 9, "", 0, 0, 'L', 0);
$pdf->Cell(5, 9, "Kepala,", 0, 0, 'L', 0); // left-align, width: 170
$pdf->ln(4);
$pdf->Cell(100, 9, "", 0, 0, 'L', 0);
$pdf->ln(23);
$pdf->Cell(100, 9, "", 0, 0, 'L', 0);
$pdf->Cell(5, 9, "Dr. Thereseta Evilianingsih,S.IP.,M.Si.", 0, 0, 'L', 0); // left-align, width: 170
$pdf->ln(5);
$pdf->Cell(100, 9, "", 0, 0, 'L', 0);
$pdf->Cell(5, 9, "NIP.  1970002061989032001", 0, 0, 'L', 0); // left-align, width: 170
$pdf->ln(35);
$pdf->SetFont('Arial', '', 6);
$pdf->ln(4);
ob_end_clean(); // don't forget this before saving the content to pdf file
$pdf->Output("surat_ket.pdf", "D"); // save and download the content to "fpdf_test.pdf" file
?>
